[wip]Feature/card
kibbang/ec-site pull request #3
Opened 2020-06-04 05:01 UTC by kibbang

カード情報を登録する作業に着手中です。

2020-06-09 01:18 UTC, sannomiyah requested changes

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/CardController.php
> +	$user = Auth::user();
インデントがおかしいです。
PHPはインデント4つ

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/CardController.php
> +	\Log::debug($card);
ログは残さないようにしてください。
他の部分も同様。

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/CardController.php
> +	$card = App\Card::create([
App\Cardはuseして使うようにしてください。
他の部分も同様

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +    public function register(Request $request){
細かいのですが、以下のように改行してください。
他の部分も同様。
```
public function register(Request $request)
{
```

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +            $query->where('name', 'like', '%'.$request->search.'%');
`.` で連結する場合は、左右に半角スペースを入れて分かりやすくしてください。

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +    public function image_upload(){
phpのメソッド名はimageUploadと言うようなキャメル記法にしてください。

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +        $request = request()->all();
ここと書き方を統一した方がみやすいです。
https://github.com/kibbang/ec-site/pull/3/files#diff-78885e013e8f99c75d566d5a16b3cb20R28

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +            return null;
失敗してもエラーとして返らないですが、問題ないですか？

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +        ->join('product_images','product_images.product_id','products.id')
',' の後は半角スペースか改行するかしてください。
他の部分も同様。

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +        $product-> update([
`->`の後の半角スペースは不要です。

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +        where('productID','[0-9]+');
これはなんですか？

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +        where('productId', '[0-9]+');
ここも処理がよく分からないです。

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +    public function productId(Request $request, string $productId){
メソッド名は再考してください。

2020-06-09 01:18 UTC, sannomiyah commented on web/app/Product.php
> +use GuzzleHttp\Psr7\Request;
これは必要ですか？

2020-06-09 01:18 UTC, sannomiyah commented on web/resources/js/components/AdminProductCard.vue
> +                <p>Product Name : {{ product.name}}</p>
{{ product.name}}
右側にもスペースを入れてもらいたいです。

2020-06-09 01:18 UTC, sannomiyah commented on web/resources/js/pages/CardRegister.vue
> +				})
インデントがおかしいです。

2020-06-09 01:18 UTC, sannomiyah commented on web/resources/js/pages/PhotoList.vue
> +		return {
ここもインデントがおかしいです。
全ファイル見直してください。

2020-06-09 01:18 UTC, sannomiyah commented on web/resources/js/pages/Shop.vue
> +				shop: ''
shopはobjectではないですか？

2020-06-09 01:18 UTC, sannomiyah commented on web/resources/js/pages/products/ProductInfo.vue
> +			  <img class="w-100" :src="product.image_url" width=150px, height=100px  alt />
widthなどの属性は`"` で囲った方が良いです。

2020-06-09 01:18 UTC, sannomiyah commented on web/resources/js/pages/Test.vue
> +    console.log('aaa');
不要なconsoleは削除してください。

2020-06-09 01:18 UTC, sannomiyah commented on web/routes/api.php
> +//Route::post('/card', 'CardController@register');
Controllerは使ってないんですか？

2020-06-11 04:49 UTC, kibbang commented on web/app/Http/Controllers/CardController.php
> +	$user = Auth::user();
修正しました。確認お願いします。

2020-06-11 04:49 UTC, kibbang commented on web/app/Http/Controllers/CardController.php
> +	\Log::debug($card);
修正しました。確認お願いします。

2020-06-11 04:49 UTC, kibbang commented on web/app/Http/Controllers/CardController.php
> +	$card = App\Card::create([
修正しました。確認お願いします。

2020-06-11 04:49 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +    public function register(Request $request){
修正しました。確認お願いします。

2020-06-11 04:50 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +            $query->where('name', 'like', '%'.$request->search.'%');
修正しました。確認お願いします。

2020-06-11 04:50 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +    public function image_upload(){
修正しました。確認お願いします。

2020-06-11 04:50 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +        $request = request()->all();
修正しました。確認お願いします。

2020-06-11 04:50 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +        ->join('product_images','product_images.product_id','products.id')
修正しました。確認お願いします。

2020-06-11 04:50 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +        $product-> update([
修正しました。確認お願いします。

2020-06-11 04:50 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +        where('productID','[0-9]+');
修正しました。確認お願いします。

2020-06-11 04:50 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +        where('productId', '[0-9]+');
修正しました。確認お願いします。

2020-06-11 04:51 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +    public function productId(Request $request, string $productId){
修正しました。確認お願いします。

2020-06-11 04:51 UTC, kibbang commented on web/app/Product.php
> +use GuzzleHttp\Psr7\Request;
修正しました。確認お願いします。

2020-06-11 04:51 UTC, kibbang commented on web/resources/js/components/AdminProductCard.vue
> +                <p>Product Name : {{ product.name}}</p>
修正しました。確認お願いします。

2020-06-11 04:51 UTC, kibbang commented on web/resources/js/pages/CardRegister.vue
> +				})
修正しました。確認お願いします。

2020-06-11 04:53 UTC, kibbang commented on web/resources/js/pages/PhotoList.vue
> +		return {
修正しました。確認お願いします。

2020-06-11 04:54 UTC, kibbang commented on web/resources/js/pages/Shop.vue
> +				shop: ''
修正しました。確認お願いします。

2020-06-11 04:54 UTC, kibbang commented on web/resources/js/pages/products/ProductInfo.vue
> +			  <img class="w-100" :src="product.image_url" width=150px, height=100px  alt />
修正しました。確認お願いします。

2020-06-11 04:54 UTC, kibbang commented on web/resources/js/pages/Test.vue
> +    console.log('aaa');
修正しました。確認お願いします。

2020-06-11 04:56 UTC, kibbang commented on web/routes/api.php
> +//Route::post('/card', 'CardController@register');
まだ使っていません

2020-06-11 04:57 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +            return null;
この部分は修正方法がよく分かりません。

2020-06-12 01:39 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +            return null;
catchでthrow $eしないと通常の問題ない200OKのレスポンスを返します。

2020-06-12 01:51 UTC, sannomiyah requested changes

2020-06-12 01:51 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +            $query->where('name', 'like', '%'.$request->search.'%');
修正されてないです。

2020-06-12 01:51 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +                App\ProductImage::create($data['product_image']);
全体的にuseにする方法に変えてください。

2020-06-12 01:51 UTC, sannomiyah commented on web/resources/js/pages/CardRegister.vue
> +			})
インデントはタブではなくてスペースにしてください。(全ファイル)

2020-06-12 01:51 UTC, sannomiyah commented on web/resources/js/pages/PhotoList.vue
> +<<template>
'<<' になっています。

2020-06-12 01:51 UTC, sannomiyah commented on web/resources/js/pages/PhotoList.vue
> +		return {
修正されてないです。

2020-06-12 01:51 UTC, sannomiyah commented on web/routes/api.php
> +	\Log::debug($card);
不要なログは消してください。

2020-06-12 01:51 UTC, sannomiyah commented on web/routes/api.php
> +        \Log::debug($product);
不要なログは消してください。

2020-06-12 01:51 UTC, sannomiyah commented on web/routes/api.php
> +    Route::post('/up', function(Request $request){
メソッド名を変えた方が良いです。

2020-06-12 01:51 UTC, sannomiyah commented on web/routes/api.php
> +        Log::debug($request->all());
不要なログは消してください。

2020-06-12 01:51 UTC, sannomiyah commented on web/resources/js/pages/products/Register.vue
> +        this.$router.push('/product/test')
testをわかりやすい名称に変更してください。

2020-06-12 01:51 UTC, sannomiyah commented on web/resources/js/pages/products/ProductEdit.vue
> +				console.log(this.product)
不要なログは削除してください。

2020-06-12 01:51 UTC, sannomiyah commented on web/app/Http/Controllers/ProductsController.php
> +        ->first()
firstやgetは一番最後に記載してください。

2020-06-12 02:54 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +                App\ProductImage::create($data['product_image']);
修正しました。確認お願いします。

2020-06-12 02:54 UTC, kibbang commented on web/resources/js/pages/CardRegister.vue
> +			})
修正しました。確認お願いします。

2020-06-12 02:54 UTC, kibbang commented on web/resources/js/pages/PhotoList.vue
> +<<template>
修正しました。確認お願いします。

2020-06-12 02:54 UTC, kibbang commented on web/routes/api.php
> +	\Log::debug($card);
修正しました。確認お願いします。

2020-06-12 02:54 UTC, kibbang commented on web/routes/api.php
> +        \Log::debug($product);
修正しました。確認お願いします。

2020-06-12 02:54 UTC, kibbang commented on web/routes/api.php
> +    Route::post('/up', function(Request $request){
修正しました。確認お願いします。

2020-06-12 02:54 UTC, kibbang commented on web/routes/api.php
> +        Log::debug($request->all());
修正しました。確認お願いします。

2020-06-12 02:55 UTC, kibbang commented on web/resources/js/pages/products/Register.vue
> +        this.$router.push('/product/test')
修正しました。確認お願いします。

2020-06-12 02:55 UTC, kibbang commented on web/resources/js/pages/products/ProductEdit.vue
> +				console.log(this.product)
修正しました。確認お願いします。

2020-06-12 02:55 UTC, kibbang commented on web/app/Http/Controllers/ProductsController.php
> +        ->first()
修正しました。確認お願いします。

2020-06-15 11:42 UTC, sannomiyah commented on web/resources/js/pages/ProductAdmin.vue
> +        searchProduct(){
これはインデントがおかしい

2020-06-15 11:57 UTC, kibbang commented on web/resources/js/pages/ProductAdmin.vue
> +        searchProduct(){
修正しました。確認お願いします。

2020-06-16 04:52 UTC, sannomiyah reviewed
LGTM!

2020-06-16 04:57 UTC, merged