[wip]Feature/account
kibbang/ec-site pull request #6
Opened 2020-06-19 03:11 UTC by kibbang

計算ページ作成中

2020-06-29 17:01 UTC, sannomiyah requested changes

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +    public function showCartPrice(Request $request)
このメソッドは何をやってるんですか？

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +    public function showDirectBuyPrice(Request $request, string $productId )
メソッドにどういう処理をするものなのかコメントを書いてください。（全てのメソッド）

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +        $fromView = $request->fromView;
使ってないならリクエストのパラメーターに含めないでください。

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +        ->join('users', 'users.id', 'cards.user_id')
なんでjoinしてるんですか？

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +        $fromView = $request->fromView;
メソッド分けたのでこれ不要じゃないですか？

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +            DB::transaction(function () use($product,$counter,$user,$productInfo,$fromView){
useは必要なものだけにしてください。

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +        $fromView = $request->fromView;
メソッド分けたのでこれ不要じゃないですか？

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +                    foreach($cartInfo as $key => $newStock){
newStockという変数名おかしいです。
下で変数名被ってるし

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +                        $newStock = $cartInfo[$key]->stock - $cartInfo[$key]->quantity;
ここはGoogle Meetsで説明したのに変わってないです。
foreachの記事を見て欲しいって言ったのに見てこの記述しか書けないんですか？

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Controllers/CardController.php
> +        ->join('users','users.id', 'cards.user_id')
なんでjoinしてるんですか？
ちゃんと考えてクエリビルダーを作ってください。

2020-06-29 17:01 UTC, sannomiyah commented on web/app/Http/Kernel.php
> +            //\App\Http\Middleware\VerifyCsrfToken::class,
本番だとこの設定はあり得ないので、TODOで開発終わったらコメントアウトを削除する旨を残してください。

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/Account.vue
> +    <div v-if="fromView == 'cartView'">
templateもscriptも全てif文で分けているので、こうするくらいならファイル分けた方が良いです。

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/Account.vue
> +      <strong>Total Price($): {{ product.price*counter }} </strong>
*の前後は半角スペースで見やすくしてください。

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/Account.vue
> +          return this.carts.reduce((acc, cart) => {
accっていうのはどういう意味でこの変数にしましたか？
あと、全体的に処理のコメントがないので記載してください。

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/Account.vue
> +        if(this.select=='')
計算式の前後は必ず半角スペース空けてください。他の箇所も

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/Account.vue
> +        if(this.fromView=='productInfoView')
productInfoViewは何もしなくてBuy Successful!になってますが、ここの処理を説明してください。

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/Account.vue
> +            this.product = response.data.product
responseの情報を格納してるのに意味はありますか？

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/Account.vue
> +            this.fromView = response.data.fromView
ここもresponseの情報を格納してるのに意味はありますか？

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/Cart.vue
> +    <button @click="goToAccountView()">Buy</button>
引数が不要であれば、()はいらないです。

2020-06-29 17:01 UTC, sannomiyah commented on web/resources/js/pages/products/ProductInfo.vue
> +          <button @click="goToAccountView()" class="btn btn-primary">Buy</button>
引数が不要であれば、()はいらないです。

2020-06-30 01:45 UTC, kibbang commented on web/resources/js/pages/Account.vue
> +      <strong>Total Price($): {{ product.price*counter }} </strong>
修正しました。

2020-06-30 01:46 UTC, kibbang commented on web/resources/js/pages/products/ProductInfo.vue
> +          <button @click="goToAccountView()" class="btn btn-primary">Buy</button>
修正しました。

2020-06-30 01:46 UTC, kibbang commented on web/resources/js/pages/Cart.vue
> +    <button @click="goToAccountView()">Buy</button>
修正しました。

2020-06-30 01:46 UTC, kibbang commented on web/app/Http/Kernel.php
> +            //\App\Http\Middleware\VerifyCsrfToken::class,
修正しました。

2020-06-30 02:16 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +        ->join('users', 'users.id', 'cards.user_id')
修正しました。

2020-06-30 02:32 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +        $fromView = $request->fromView;
修正しました。

2020-06-30 02:34 UTC, kibbang commented on web/app/Http/Controllers/CardController.php
> +        ->join('users','users.id', 'cards.user_id')
修正しました。

2020-06-30 02:49 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +    public function showCartPrice(Request $request)
修正しました。

2020-06-30 02:51 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +        $fromView = $request->fromView;
修正しました。

2020-06-30 05:23 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +        $fromView = $request->fromView;
修正しました。

2020-06-30 05:24 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +            DB::transaction(function () use($product,$counter,$user,$productInfo,$fromView){
修正しました。

2020-06-30 05:35 UTC, kibbang commented on web/resources/js/pages/Account.vue
> +            this.product = response.data.product
修正しました。

2020-06-30 05:35 UTC, kibbang commented on web/resources/js/pages/Account.vue
> +            this.fromView = response.data.fromView
修正しました。

2020-06-30 05:58 UTC, kibbang commented on web/resources/js/pages/Account.vue
> +        if(this.fromView=='productInfoView')
あのif文がなければカートで購入する場合、直接クリックしたcounterが0なのでalertが発生します。ですからparamsがproductInfoViewのときだけカウンターを数えるために作成しました。

2020-06-30 06:04 UTC, kibbang commented on web/resources/js/pages/Account.vue
> +        if(this.select=='')
修正しました。

2020-06-30 06:15 UTC, kibbang commented on web/resources/js/pages/Account.vue
> +          return this.carts.reduce((acc, cart) => {
accumulatorの略でした。 わかりやすくtotalに変えました。

2020-06-30 06:54 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +                    foreach($cartInfo as $key => $newStock){
修正しました。

2020-06-30 06:55 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +                        $newStock = $cartInfo[$key]->stock - $cartInfo[$key]->quantity;
修正しました。

2020-06-30 07:24 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +    public function showDirectBuyPrice(Request $request, string $productId )
修正しました。

2020-06-30 08:08 UTC, kibbang commented on web/resources/js/pages/Account.vue
> +    <div v-if="fromView == 'cartView'">
ページを分けて処理しました。

2020-06-30 08:32 UTC, sannomiyah requested changes

2020-06-30 08:32 UTC, sannomiyah commented on web/routes/api.php
> +Route::get('/account', 'AccountController@showCartPrice');
これ必要ですか？

2020-06-30 08:32 UTC, sannomiyah commented on web/routes/api.php
> +Route::get('/account/{product}', 'AccountController@showDirectBuyPrice');
これも必要ですか？

2020-06-30 08:32 UTC, sannomiyah commented on web/routes/api.php
> +Route::get('/account/card', 'AccountController@cardSelect');
これも必要ですか？

2020-06-30 08:32 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +                    foreach($cartInfo as $key => $orderInfo){
インデント変えてください。

2020-06-30 08:32 UTC, sannomiyah commented on web/app/Http/Controllers/CardController.php
> +    //カード番号の表示(カード選択のため)
メソッドのコメントアウトは以下で統一してください。
```
/**
 *
 **/
```

2020-06-30 08:32 UTC, sannomiyah commented on web/resources/js/pages/AccountCart.vue
> +    <div v-if="fromView == 'cartView'">
ファイル分けたのにif文は必要ですか？

2020-06-30 08:32 UTC, sannomiyah commented on web/resources/js/pages/AccountProduct.vue
> +      if(this.fromView=='productInfoView')
これも必要ですか？

2020-06-30 08:32 UTC, sannomiyah commented on web/resources/js/pages/AccountProduct.vue
> +          alert('Buy Successful!')
ここにBuy Successful!をつけるのはおかしいです。
axiosで失敗したときに買えてないのにsuccessになります。

2020-06-30 08:32 UTC, sannomiyah commented on web/resources/js/pages/AccountCart.vue
> +          alert('Buy Successful!')
ここにBuy Successful!をつけるのはおかしいです。
axiosで失敗したときに買えてないのにsuccessになります。

2020-06-30 08:35 UTC, kibbang commented on web/routes/api.php
> +Route::get('/account', 'AccountController@showCartPrice');
修正しました。

2020-06-30 08:35 UTC, kibbang commented on web/routes/api.php
> +Route::get('/account/{product}', 'AccountController@showDirectBuyPrice');
修正しました。

2020-06-30 08:35 UTC, kibbang commented on web/routes/api.php
> +Route::get('/account/card', 'AccountController@cardSelect');
修正しました。

2020-06-30 08:37 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +                    foreach($cartInfo as $key => $orderInfo){
修正しました。

2020-06-30 08:39 UTC, kibbang commented on web/resources/js/pages/AccountCart.vue
> +    <div v-if="fromView == 'cartView'">
修正しました。

2020-06-30 08:40 UTC, kibbang commented on web/resources/js/pages/AccountProduct.vue
> +      if(this.fromView=='productInfoView')
修正しました。

2020-06-30 09:10 UTC, kibbang commented on web/app/Http/Controllers/CardController.php
> +    //カード番号の表示(カード選択のため)
修正しました。

2020-06-30 10:05 UTC, kibbang commented on web/resources/js/pages/AccountProduct.vue
> +          alert('Buy Successful!')
修正しました。

2020-06-30 10:05 UTC, kibbang commented on web/resources/js/pages/AccountCart.vue
> +          alert('Buy Successful!')
修正しました。

2020-06-30 11:15 UTC, sannomiyah commented on web/app/Http/Controllers/AccountController.php
> +    /**商品をカートに入れずに直接購入する場合実行**/
この形式に合わせてください。
```
/**
 *
 */
```

2020-06-30 11:15 UTC, sannomiyah commented on web/resources/js/pages/products/Register.vue
> +        /**DBに登録する処理**/
伝え方が良くなかったけど、jsは1行であれば `//` でOKです。

2020-06-30 12:43 UTC, kibbang commented on web/app/Http/Controllers/AccountController.php
> +    /**商品をカートに入れずに直接購入する場合実行**/
修正しました。

2020-06-30 12:43 UTC, kibbang commented on web/resources/js/pages/products/Register.vue
> +        /**DBに登録する処理**/
修正しました。

2020-06-30 15:27 UTC, sannomiyah approved these changes
LGTM!

2020-06-30 15:28 UTC, merged